version: "3.9"

services:
  valentine:
    build: .
    container_name: valentine_service

    environment:
      - PORT=5000

    ports:
      - "${PORT}:5000"

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

    mem_limit: 256m
    cpus: 0.5

